name: listdemo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.11.3+17
  flutter_pdf_viewer: ^0.0.2
  charcode: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Images/
    - Images/imageedit_26_8716278705.png
    - asset/OISI Navy Library Engineering/
    - asset/OISI Navy Library Logistics/
    - asset/OISI Navy Library Medical/
    - asset/OISI Navy Library Warfare/

